# =========================================
# Hyperparameters for training
# =========================================

model: vgg16
num_classes: 4
batch_size: 64
learning_rate: 0.003
epochs: 30
dropout: 0.5
patience: 12
step_size: 5
gamma: 0.1
checkpoint_interval: 5

# Paths
data_dir: ../data/
drive_base: /content/drive/MyDrive/alzheimers_project
